backend/app/controllers/users.py
from flask import jsonify, render_template, redirect, url_for, flash, request
from werkzeug.urls import url_parse
from flask_login import login_user, logout_user, current_user
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo

from ..models.user import User


from flask import Blueprint

bp = Blueprint("users", __name__)


@bp.route("/login", methods=["GET", "POST"])
def login():
    data = request.get_json()
    email = data.get("email")
    password = data.get("password")
    user = User.get_by_auth(email, password)
    if user is None:
        return jsonify({"message": "Failed to login"}), 400
    
    return jsonify({"message": "Registration complete"}), 201

@bp.route("/signup", methods=["POST"])
def register():
    data = request.get_json()
    email = data.get("email")
    password = data.get("password")
    firstname = data.get("firstname")
    lastname = data.get("lastname")

    if User.email_exists(email):
        return jsonify({"message": "Account with email already exists"}), 400

    User.register(email, password, firstname, lastname)
    return jsonify({"message": "Registration complete"}), 201


@bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("index.index"))

backend/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Mini Amazon</title>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/example.css') }}">
  <style>
    body {
        font-family: "Lato", sans-serif;
    }

    .main-head {
        height: 150px;
        background: #FFF;
    }

    .sidenav {
        height: 100%;
        background-color: #000;
        overflow-x: hidden;
        padding-top: 20px;
    }

    .main {
        padding: 0px 10px;
    }

    .login-main-text {
        margin-top: 20%;
        padding: 60px;
        color: #fff;
    }

    .login-main-text h2 {
        font-weight: 300;
    }

    .btn-black {
        background-color: #000 !important;
        color: #fff;
    }
  </style>
</head>

<body>
  <div class="sidenav">
    {% block msg %}
      <h1 style="color:aliceblue">Welcome to CompSci 316 Mini Amazon!</h1>
      <div style="color: aliceblue; text-align: right; margin-bottom: 25px">
        {% if current_user.is_authenticated %}
          Hello {{current_user.firstname}}! <a href="{{ url_for('users.logout') }}" type="button" class="btn btn-light">Log out</a>
        {% else %}
          <a href="{{ url_for('users.login') }}" type="button" class="btn btn-light">Log in</a>
        {% endif %}
      </div>
    {% endblock %}
  </div>
  <div class="main">
    {% block content %}{% endblock %}
  </div>
</body>

</html>

backend/app/templates/index.html
{% extends "base.html" %}

{% block content %}

<br><br>

<h2>Products for sale:</h2>
<table class='table table-hover table-bordered container'>
  <thead class="thead-dark">
    <tr>
      <th scope="col">Product ID</th>
      <th scope="col">Product Name</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
    {% for product in avail_products%}
      <tr>
        <th scope="row">{{product.id}}</th>
        <td>{{product.name}}</td>
        <td>{{product.price}}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

<br><br>
{% if current_user.is_authenticated %}
<h2>Your recent purchases:</h2>
<table class='table table-hover table-bordered container'>
  <thead class="thead-dark">
    <tr>
      <th scope="col">Purchase ID</th>
      <th scope="col">Product Name</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
    {% for purchase in purchase_history%}
      <tr>
        <th scope="row">{{purchase.id}}</th>
        <td>{{purchase.pid}}</td>
        <td>{{purchase.time_purchased}}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p><a href="{{ url_for('users.login') }}">Log in</a> to see your purchase history!</p>
{% endif %}

{% endblock %}

backend/app/templates/login.html
{% extends "base.html" %}

{% block content %}

<h1>Login</h1>

<form action="" method="post" novalidate>
  {{ form.hidden_tag() }}
  <p>
    {{ form.email.label }}<br/>
    {{ form.email(size=32) }}<br/>
    {% for error in form.email.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>
    {{ form.password.label }}<br/>
    {{ form.password(size=32) }}<br/>
    {% for error in form.password.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
  </p>
  {{ form.submit(class_="btn btn-black") }}
  <a class="btn btn-secondary" href="{{ url_for('users.register') }}" role="button">Register</a>
</form>

{% endblock %}

backend/app/templates/register.html
{% extends "base.html" %}

{% block content %}

<h1>Register</h1>

<form action="" method="post">
  {{ form.hidden_tag() }}
  <p>
    {{ form.firstname.label }}<br/>
    {{ form.firstname(size=32) }}<br/>
    {% for error in form.firstname.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>
    {{ form.lastname.label }}<br/>
    {{ form.lastname(size=32) }}<br/>
    {% for error in form.lastname.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>
    {{ form.email.label }} (Could be fake email address)<br/>
    {{ form.email(size=64) }}<br/>
    {% for error in form.email.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>
    {{ form.password.label }}<br/>
    {{ form.password(size=32) }}<br/>
    {% for error in form.password.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>
    {{ form.password2.label }}<br/>
    {{ form.password2(size=32) }}<br/>
    {% for error in form.password2.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
  </p>
  <p>{{ form.submit() }}</p>
</form>

{% endblock %}